#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <math.h>
#define W 10
#define H 20
#define CELLS 200
#define PREVIEW 16
#define FRAME 417
#define ACTS 4
#define FD 52
#define BR 3
#define TBITS 19
#define TSZ (1u<<TBITS)
#define MASK (TSZ-1u)
enum{ACT_NONE=0,ACT_LEFT,ACT_RIGHT,ACT_ROT};enum{EV_MOVE=1,EV_ROT=2,EV_LOCK=8,EV_CLEAR=16,EV_GAMEOVER=32};
typedef struct{uint64_t s;}RNG;static uint32_t ru(RNG*r){r->s^=r->s>>12;r->s^=r->s<<25;r->s^=r->s>>27;return(uint32_t)((r->s*2685821657736338717ULL)>>32);}static int ri(RNG*r,int n){return n?(int)(ru(r)%(uint32_t)n):0;}static float rf(RNG*r){return(ru(r)+.5f)/4294967296.f;}static uint32_t mix(uint32_t x){x^=x>>16;x*=0x7feb352dU;x^=x>>15;x*=0x846ca68bU;x^=x>>16;return x;}
static const uint16_t SH[7][4]={{0x00F0,0x4444,0x00F0,0x4444},{0x0660,0x0660,0x0660,0x0660},{0x0270,0x0262,0x0720,0x0232},{0x0360,0x0462,0x0360,0x0462},{0x0630,0x0264,0x0630,0x0264},{0x0710,0x0226,0x0470,0x0322},{0x0740,0x0622,0x0170,0x0223}};static int oc(uint16_t m,int x,int y){return(m>>(y*4+x))&1;}
typedef struct{uint16_t row[H];int type,rot,x,y,next_type,game_over,lines,pieces;}Game;static int col(const Game*g,int type,int rot,int x,int y){uint16_t m=SH[type][rot&3];for(int sy=0;sy<4;sy++)for(int sx=0;sx<4;sx++)if(oc(m,sx,sy)){int bx=x+sx,by=y+sy;if(bx<0||bx>=W||by>=H)return 1;if(by>=0&&(g->row[by]&(1u<<bx)))return 1;}return 0;}static int spawn(Game*g){g->type=g->next_type;g->next_type=(g->next_type+1)%7;g->rot=0;g->x=3;g->y=-1;g->pieces++;if(col(g,g->type,g->rot,g->x,g->y)){g->game_over=1;return 0;}return 1;}static void init(Game*g,int s){memset(g,0,sizeof(*g));g->next_type=s%7;spawn(g);}static int clr(Game*g){int n=0;for(int y=H-1;y>=0;y--)if((g->row[y]&1023u)==1023u){for(int z=y;z>0;z--)g->row[z]=g->row[z-1];g->row[0]=0;n++;y++;}g->lines+=n;return n;}static int lockp(Game*g){uint16_t m=SH[g->type][g->rot&3];for(int sy=0;sy<4;sy++)for(int sx=0;sx<4;sx++)if(oc(m,sx,sy)){int x=g->x+sx,y=g->y+sy;if(y<0){g->game_over=1;return EV_LOCK|EV_GAMEOVER;}if(x>=0&&x<W&&y<H)g->row[y]|=1u<<x;}int e=EV_LOCK;if(clr(g))e|=EV_CLEAR;if(!spawn(g))e|=EV_GAMEOVER;return e;}static int step(Game*g,int a){if(g->game_over)return EV_GAMEOVER;int e=0;if(a==ACT_LEFT&&!col(g,g->type,g->rot,g->x-1,g->y)){g->x--;e|=EV_MOVE;}else if(a==ACT_RIGHT&&!col(g,g->type,g->rot,g->x+1,g->y)){g->x++;e|=EV_MOVE;}else if(a==ACT_ROT&&!col(g,g->type,(g->rot+1)&3,g->x,g->y)){g->rot=(g->rot+1)&3;e|=EV_ROT;}if(!col(g,g->type,g->rot,g->x,g->y+1))g->y++;else e|=lockp(g);return e;}static void render(const Game*g,uint8_t f[FRAME]){memset(f,0,FRAME);for(int y=0;y<H;y++)for(int x=0;x<W;x++)f[y*W+x]=(g->row[y]>>x)&1;if(!g->game_over){uint16_t m=SH[g->type][g->rot&3];for(int sy=0;sy<4;sy++)for(int sx=0;sx<4;sx++)if(oc(m,sx,sy)){int x=g->x+sx,y=g->y+sy;if(x>=0&&x<W&&y>=0&&y<H)f[CELLS+y*W+x]=1;}}uint16_t p=SH[g->next_type][0];for(int y=0;y<4;y++)for(int x=0;x<4;x++)f[400+y*4+x]=oc(p,x,y);f[416]=(uint8_t)g->game_over;}
typedef struct{int tr,tx,v,last;}Pilot;static int holes(const Game*g){int h=0;for(int x=0;x<W;x++){int seen=0;for(int y=0;y<H;y++){if(g->row[y]&(1u<<x))seen=1;else if(seen)h++;}}return h;}static int hei(const Game*g){int s=0;for(int x=0;x<W;x++){int h=0;for(int y=0;y<H;y++)if(g->row[y]&(1u<<x)){h=H-y;break;}s+=h;}return s;}static int land(const Game*g,int t,int r,int x){int y=-2;if(col(g,t,r,x,y))return 999;while(!col(g,t,r,x,y+1))y++;return y;}static void choose(const Game*g,Pilot*p,RNG*r){float best=-1e30f;int br=0,bx=3;for(int ro=0;ro<4;ro++)for(int x=-2;x<W;x++){int y=land(g,g->type,ro,x);if(y==999)continue;Game q=*g;q.rot=ro;q.x=x;q.y=y;q.game_over=0;int b=q.lines;lockp(&q);float sc=120.f*(q.lines-b)-8.f*holes(&q)-.6f*hei(&q)+(rf(r)-.5f)*10;if(sc>best){best=sc;br=ro;bx=x;}}p->tr=br;p->tx=bx;p->v=1;p->last=g->pieces;}static int pol(const Game*g,Pilot*p,RNG*r,int ex){if(g->game_over)return 0;if(!p->v||p->last!=g->pieces)choose(g,p,r);if(ex&&ri(r,100)<22)return ri(r,ACTS);if(g->rot!=p->tr)return ACT_ROT;if(g->x<p->tx)return ACT_RIGHT;if(g->x>p->tx)return ACT_LEFT;return ACT_NONE;}
typedef struct{float w[ACTS][FD];unsigned long long writes;}FC;
static float fsig(float x){if(x>12.f)return .999994f;if(x<-12.f)return .000006f;return 1.f/(1.f+expf(-x));}
static void ftarget(const uint8_t*a,const uint8_t*b,float t[FD]){for(int k=0;k<FD;k++)t[k]=0.f;int s=0;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(a[CELLS+y*W+x]){s++;for(int dy=-2;dy<=2;dy++)for(int dx=-2;dx<=2;dx++){int xx=x+dx,yy=y+dy,k=(dy+2)*5+dx+2;if(xx>=0&&xx<W&&yy>=0&&yy<H){t[k]+=b[CELLS+yy*W+xx];t[25+k]+=b[yy*W+xx];}}}if(s<1)s=1;for(int k=0;k<50;k++)t[k]/=(float)s;int pc=0;for(int k=0;k<16;k++)pc+=a[400+k]!=b[400+k];t[50]=pc>0?1.f:0.f;t[51]=b[416]?1.f:0.f;}
static void fpred(const FC*c,int ac,float p[FD]){for(int k=0;k<FD;k++)p[k]=fsig(c->w[ac][k]);}
static void fobs(FC*c,const uint8_t*a,int ac,const uint8_t*b){float t[FD],p[FD];ftarget(a,b,t);fpred(c,ac,p);const float lr=.42f;for(int k=0;k<FD;k++){float e=t[k]-p[k];c->w[ac][k]+=lr*e;if(c->w[ac][k]>12.f)c->w[ac][k]=12.f;if(c->w[ac][k]<-12.f)c->w[ac][k]=-12.f;c->writes++;}}
static void fw(const FC*c,int ac,float q[FD]){double n=0;for(int k=0;k<FD;k++){q[k]=fsig(c->w[ac][k]);n+=q[k]*q[k];}n=sqrt(n);if(n<1e-9)n=1;for(int k=0;k<FD;k++)q[k]/=(float)n;}
static uint32_t fh(const float*q,int salt){uint32_t h=0x9e3779b9u^(uint32_t)salt*0x85ebca6bu;for(int p=0;p<8;p++){double s=0;for(int k=0;k<FD;k++)s+=((mix((uint32_t)(k*131+p*977+17))&1)?1.:-1.)*q[k];h=mix(h^((uint32_t)(s>0)+0x100u*(p+1)));}return h;}
#define RBITS 20
#define RSZ (1u<<RBITS)
#define RMASK (RSZ-1u)
typedef struct{float*w[BR];}QC;typedef struct{uint32_t a[BR][FRAME];}Cache;
static void qi(QC*q){for(int b=0;b<BR;b++){q->w[b]=calloc(RSZ,sizeof(float));if(!q->w[b])exit(2);}}
static void qf(QC*q){for(int b=0;b<BR;b++)free(q->w[b]);}
static uint32_t patch3(const uint8_t*f,int x,int y){uint32_t v=0,b=0;for(int pl=0;pl<2;pl++)for(int dy=-1;dy<=1;dy++)for(int dx=-1;dx<=1;dx++){int xx=x+dx,yy=y+dy;uint32_t bit=(xx<0||xx>=W||yy<0||yy>=H)?1u:f[pl*CELLS+yy*W+xx];v|=bit<<b++;}return v;}
static uint32_t row2(const uint8_t*f,int y){uint32_t a=0,b=0;for(int pl=0;pl<2;pl++)for(int x=0;x<W;x++)a|=(uint32_t)f[pl*CELLS+y*W+x]<<b++;uint32_t c=0,d=0;if(y>0)for(int pl=0;pl<2;pl++)for(int x=0;x<W;x++)c|=(uint32_t)f[pl*CELLS+(y-1)*W+x]<<d++;return mix(a)^mix(c+0x13579u);}
static uint32_t col5(const uint8_t*f,int x,int y){uint32_t v=0,b=0;for(int pl=0;pl<2;pl++)for(int dy=-2;dy<=2;dy++){int yy=y+dy;uint32_t bit=(yy<0||yy>=H)?1u:f[pl*CELLS+yy*W+x];v|=bit<<b++;}return v;}
static uint32_t prev16(const uint8_t*f){uint32_t v=0;for(int k=0;k<16;k++)v|=(uint32_t)f[400+k]<<k;return v;}
static uint32_t top_hash(const uint8_t*f){uint32_t h=1;for(int y=0;y<6;y++)for(int x=0;x<W;x++)h=mix(h^((uint32_t)f[y*W+x]+3u*f[CELLS+y*W+x]+13u*x+67u*y));return h;}
static uint32_t bot_hash(const uint8_t*f){uint32_t h=7;for(int y=H-5;y<H;y++)for(int x=0;x<W;x++)h=mix(h^((uint32_t)f[y*W+x]+17u*x+73u*y));return h;}
static void cache(const uint8_t*f,const float*fun,Cache*c){uint32_t F[BR];for(int b=0;b<BR;b++)F[b]=fh(fun,b+11);uint32_t pv=prev16(f),th=top_hash(f),bh=bot_hash(f);for(int j=0;j<FRAME;j++){if(j<CELLS*2){int plane=j/CELLS,k=j%CELLS,x=k%W,y=k/W;uint32_t p=patch3(f,x,y),r=row2(f,y),cl=col5(f,x,y);c->a[0][j]=mix(F[0]^p^(uint32_t)(plane*0x51ed2705u))&RMASK;c->a[1][j]=mix(F[1]^r^(uint32_t)(plane*0x9e3779b9u))&RMASK;c->a[2][j]=mix(F[2]^cl^mix(pv+0x10001u*plane))&RMASK;}else{uint32_t oi=(uint32_t)(j-400);c->a[0][j]=mix(F[0]^pv^oi*0x9e3779b9u)&RMASK;c->a[1][j]=mix(F[1]^th^oi*0x85ebca6bu)&RMASK;c->a[2][j]=mix(F[2]^bh^pv^oi*0xc2b2ae35u)&RMASK;}}}
static void funcbase(const uint8_t*in,const float*fun,float*out){for(int j=0;j<FRAME;j++)out[j]=(float)in[j];for(int j=CELLS;j<CELLS*2;j++)out[j]=0;double ww[25],sum=0;for(int k=0;k<25;k++){double x=fun[k];if(x<0)x=0;ww[k]=pow(x,10.0);sum+=ww[k];}if(sum<1e-16){for(int j=CELLS;j<CELLS*2;j++)out[j]=in[j];return;}for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(in[CELLS+y*W+x])for(int dy=-2;dy<=2;dy++)for(int dx=-2;dx<=2;dx++){int xx=x+dx,yy=y+dy;if(xx<0||xx>=W||yy<0||yy>=H)continue;float p=(float)(ww[(dy+2)*5+dx+2]/sum);int j=CELLS+yy*W+xx;out[j]=1.f-(1.f-out[j])*(1.f-p);}}
static void predq(const QC*q,const Cache*c,const uint8_t*in,const float*fun,float*p){funcbase(in,fun,p);for(int j=0;j<FRAME;j++){float r=0;for(int b=0;b<BR;b++)r+=q->w[b][c->a[b][j]];p[j]+=r/BR;if(p[j]<.001f)p[j]=.001f;if(p[j]>.999f)p[j]=.999f;}}
static void trainq(QC*q,const Cache*c,const uint8_t*in,const float*fun,const uint8_t*t){float p[FRAME];predq(q,c,in,fun,p);for(int j=0;j<FRAME;j++){float e=(float)t[j]-p[j],d=.24f*e/BR;for(int b=0;b<BR;b++){float*w=&q->w[b][c->a[b][j]];*w+=d;if(*w>1.5f)*w=1.5f;if(*w<-1.5f)*w=-1.5f;}}}
typedef struct{uint64_t n,ex,bits,cor,tp,fp,fn,evn[5],eve[5];}M;static void madd(M*m,const uint8_t*in,const uint8_t*t,const float*p,int ev){int ex=1;for(int j=0;j<FRAME;j++){int q=p[j]>=.5,y=t[j];m->bits++;m->cor+=q==y;if(q!=y)ex=0;int tc=t[j]!=in[j],pc=q!=in[j];if(pc&&tc)m->tp++;else if(pc&&!tc)m->fp++;else if(!pc&&tc)m->fn++;}m->n++;m->ex+=ex;int fl[5]={EV_MOVE,EV_ROT,EV_LOCK,EV_CLEAR,EV_GAMEOVER};for(int i=0;i<5;i++)if(ev&fl[i]){m->evn[i]++;m->eve[i]+=ex;}}static void mp(const char*s,const M*m){double pr=(m->tp+m->fp)?(double)m->tp/(m->tp+m->fp):0,re=(m->tp+m->fn)?(double)m->tp/(m->tp+m->fn):0,f=(pr+re)?2*pr*re/(pr+re):0;printf("[%s] frame=%.3f bit=%.3f f1=%.3f",s,100.0*m->ex/m->n,100.0*m->cor/m->bits,f);const char*n[5]={"move","rot","lock","clear","over"};for(int i=0;i<5;i++)if(m->evn[i])printf(" %s=%.2f(%llu)",n[i],100.0*m->eve[i]/m->evn[i],(unsigned long long)m->evn[i]);puts("");}
static void eval(const FC*fc,const QC*q,int N,uint64_t seed,int ab,const char*tag){RNG r={seed};Game g;init(&g,ri(&r,7));Pilot po={0};uint8_t a[FRAME],t[FRAME];float fun[FD],pr[FRAME];Cache c;M m={0};for(int i=0;i<N;i++){if(g.game_over){init(&g,ri(&r,7));memset(&po,0,sizeof(po));}render(&g,a);int ac=pol(&g,&po,&r,1);int ev=step(&g,ac);render(&g,t);fw(fc,ac,fun);if(ab==1)memset(fun,0,sizeof(fun));else if(ab==2)for(int k=0;k<FD;k++)fun[k]=-fun[k];else if(ab==3){float x=fun[0];for(int k=0;k<FD-1;k++)fun[k]=fun[k+1];fun[FD-1]=x;}cache(a,fun,&c);predq(q,&c,a,fun,pr);madd(&m,a,t,pr,ev);}mp(tag,&m);}
int main(int argc,char**argv){int warm=argc>1?atoi(argv[1]):12000,tr=argc>2?atoi(argv[2]):50000,ev=argc>3?atoi(argv[3]):5000;FC fc={0};QC q;qi(&q);RNG r={0x1234567};Game g;init(&g,ri(&r,7));Pilot po={0};uint8_t a[FRAME],t[FRAME];for(int i=0;i<warm;i++){if(g.game_over){init(&g,ri(&r,7));memset(&po,0,sizeof(po));}render(&g,a);int ac=pol(&g,&po,&r,1);step(&g,ac);render(&g,t);fobs(&fc,a,ac,t);}printf("direct-full-tetris ERROR-WRITEBACK function-cube warm=%d train=%d\n",warm,tr);for(int i=0;i<tr;i++){if(g.game_over){init(&g,ri(&r,7));memset(&po,0,sizeof(po));}render(&g,a);int ac=pol(&g,&po,&r,1);step(&g,ac);render(&g,t);float fun[FD];Cache c;fw(&fc,ac,fun);cache(a,fun,&c);trainq(&q,&c,a,fun,t);if((i+1)%10000==0){char s[32];snprintf(s,sizeof(s),"hold@%d",i+1);eval(&fc,&q,1500,0xABC000u+(uint64_t)i,0,s);}}eval(&fc,&q,ev,0xDEADBEEFu,0,"final");eval(&fc,&q,ev,0xDEADBEEFu,1,"F-zero");eval(&fc,&q,ev,0xDEADBEEFu,2,"F-flip");eval(&fc,&q,ev,0xDEADBEEFu,3,"F-shift");qf(&q);return 0;}
