#define main direct_v011_hidden_main
#include "base_v011.c"
#undef main

#define F2D 68
#define F2B 3
#define F2BITS 15
#define F2SZ (1u<<F2BITS)
#define F2MASK (F2SZ-1u)
#define C3B 3
#define C3BITS 19
#define C3SZ (1u<<C3BITS)
#define C3MASK (C3SZ-1u)

typedef struct{float *w[F2B];unsigned long long writes;}F2Cube;
typedef struct{float *w[C3B];unsigned long long writes;}C3Cube;
typedef struct{uint32_t a[C3B][FRAME];}C3Cache;
static void f2init(F2Cube*c){memset(c,0,sizeof(*c));for(int b=0;b<F2B;b++){c->w[b]=calloc((size_t)F2SZ*F2D,sizeof(float));if(!c->w[b])exit(2);}}
static void f2free(F2Cube*c){for(int b=0;b<F2B;b++)free(c->w[b]);}
static void c3init(C3Cube*c){memset(c,0,sizeof(*c));for(int b=0;b<C3B;b++){c->w[b]=calloc(C3SZ,sizeof(float));if(!c->w[b])exit(2);}}
static void c3free(C3Cube*c){for(int b=0;b<C3B;b++)free(c->w[b]);}
static void pbits(const float*p,uint8_t*b){for(int j=0;j<FRAME;j++)b[j]=(uint8_t)(p[j]>=.5f);}
static uint32_t fhash68(const float*q,int salt){uint32_t h=0x243f6a88u^(uint32_t)salt*0x9e3779b9u;for(int p=0;p<10;p++){double s=0;for(int k=0;k<F2D;k++){uint32_t r=mix((uint32_t)(k*313+p*1193+salt*17));s+=((r&1u)?1.:-1.)*q[k];}h=mix(h^((uint32_t)(s>0)+0x100u*(p+1)));}return h;}

static float compat_wave13(const uint8_t*f,const float*fun){double ww[25],sum=0;for(int k=0;k<25;k++){double x=fun[k];if(x<0)x=0;ww[k]=pow(x,10.0);sum+=ww[k];}if(sum<1e-16)return 0.f;for(int k=0;k<25;k++)ww[k]/=sum;double C=1.0;int n=0;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(f[CELLS+y*W+x]){double pass=0;for(int dy=-2;dy<=2;dy++)for(int dx=-2;dx<=2;dx++){double w=ww[(dy+2)*5+dx+2];if(w<1e-12)continue;int xx=x+dx,yy=y+dy;int free=(xx>=0&&xx<W&&yy>=0&&yy<H&&!f[yy*W+xx]);if(free)pass+=w;}C*=pass;n++;}if(!n)return 1.f;if(C<0)C=0;if(C>1)C=1;return(float)C;}
static uint32_t active_rel_pool(const uint8_t*f,const uint8_t*pb){uint32_t h=0x6a09e667u;int n=0;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(f[CELLS+y*W+x]){uint32_t a=patch3(f,x,y),b=patch3(pb,x,y);h^=mix(a^mix(b+0x9e3779b9u)^(uint32_t)(n+1)*0x85ebca6bu);n++;}return mix(h^(uint32_t)n*0xc2b2ae35u);}
static uint32_t contact_pool(const uint8_t*f,const uint8_t*pb){uint32_t h=0x510e527fu;int n=0;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(f[CELLS+y*W+x]){uint32_t v=0,bit=0;for(int dy=-2;dy<=2;dy++)for(int dx=-2;dx<=2;dx++){int xx=x+dx,yy=y+dy;uint32_t q=(xx<0||xx>=W||yy<0||yy>=H)?3u:(uint32_t)f[yy*W+xx]+2u*(uint32_t)pb[CELLS+yy*W+xx];v^=mix(q+17u*(bit+1));bit++;}h^=mix(v+(uint32_t)(n+1)*0x27d4eb2du);n++;}return mix(h^(uint32_t)n*0x165667b1u);}
static void f2addrs(const uint8_t*f,const float*p1,const float*fun,uint32_t a[F2B]){uint8_t pb[FRAME];pbits(p1,pb);uint32_t F=fh(fun,31),pv=prev16(f),pp=prev16(pb),ar=active_rel_pool(f,pb),cp=contact_pool(f,pb);float cw=compat_wave13(f,fun);uint32_t cq=(uint32_t)(cw*15.999f);a[0]=mix(F^ar^mix(pv+0x10001u*pp)^mix(cq*0x9e3779b9u))&F2MASK;a[1]=mix(F^cp^mix(bot_hash(f))^mix(bot_hash(pb)+0x314159u)^mix(cq*0x85ebca6bu))&F2MASK;a[2]=mix(F^mix(top_hash(f))^mix(top_hash(pb)+0x271828u)^mix(pv)^mix(pp+7)^mix(cq*0xc2b2ae35u))&F2MASK;}
static void residual_target(const uint8_t*cur,const float*p1,const uint8_t*tar,float out[F2D]){for(int k=0;k<F2D;k++)out[k]=0.f;int s=0;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(cur[CELLS+y*W+x]){s++;for(int dy=-2;dy<=2;dy++)for(int dx=-2;dx<=2;dx++){int xx=x+dx,yy=y+dy,k=(dy+2)*5+dx+2;if(xx>=0&&xx<W&&yy>=0&&yy<H){out[k]+=(float)tar[CELLS+yy*W+xx]-p1[CELLS+yy*W+xx];out[25+k]+=(float)tar[yy*W+xx]-p1[yy*W+xx];}}}if(s<1)s=1;for(int k=0;k<50;k++)out[k]/=(float)s;for(int k=0;k<16;k++)out[50+k]=(float)tar[400+k]-p1[400+k];out[66]=(float)tar[416]-p1[416];double e=0;for(int j=0;j<FRAME;j++){double d=(double)tar[j]-p1[j];e+=d*d;}out[67]=(float)sqrt(e/FRAME);}
static void f2pred(const F2Cube*c,const uint32_t a[F2B],float out[F2D]){for(int k=0;k<F2D;k++){float z=0;for(int b=0;b<F2B;b++)z+=c->w[b][(size_t)a[b]*F2D+k];out[k]=z/F2B;}}
static void f2train(F2Cube*c,const uint32_t a[F2B],const float target[F2D]){float p[F2D];f2pred(c,a,p);for(int k=0;k<F2D;k++){float e=target[k]-p[k],d=.18f*e/F2B;for(int b=0;b<F2B;b++){float*w=&c->w[b][(size_t)a[b]*F2D+k];*w+=d;if(*w>2.f)*w=2.f;if(*w<-2.f)*w=-2.f;c->writes++;}}}
static void c3cache_build(const uint8_t*f,const float*p1,const float*f2,C3Cache*c){uint8_t pb[FRAME];pbits(p1,pb);uint32_t F[C3B];for(int b=0;b<C3B;b++)F[b]=fhash68(f2,b+41);uint32_t pv=prev16(f),pp=prev16(pb),th=top_hash(f),tph=top_hash(pb),bh=bot_hash(f),bph=bot_hash(pb);for(int j=0;j<FRAME;j++){if(j<CELLS*2){int plane=j/CELLS,k=j%CELLS,x=k%W,y=k/W;uint32_t p=patch3(f,x,y),p2=patch3(pb,x,y),r=row2(f,y)^mix(row2(pb,y)+7),cl=col5(f,x,y)^mix(col5(pb,x,y)+11);c->a[0][j]=mix(F[0]^p^mix(p2+0x1111u)^(uint32_t)plane*0x51ed2705u)&C3MASK;c->a[1][j]=mix(F[1]^r^(uint32_t)plane*0x9e3779b9u)&C3MASK;c->a[2][j]=mix(F[2]^cl^mix(pv+0x10001u*pp)^(uint32_t)plane*0xc2b2ae35u)&C3MASK;}else{uint32_t oi=(uint32_t)(j-400);c->a[0][j]=mix(F[0]^pv^mix(pp+3)^oi*0x9e3779b9u)&C3MASK;c->a[1][j]=mix(F[1]^th^mix(tph+5)^oi*0x85ebca6bu)&C3MASK;c->a[2][j]=mix(F[2]^bh^mix(bph+13)^pv^oi*0xc2b2ae35u)&C3MASK;}}}
static void c3pred(const C3Cube*c,const C3Cache*ca,const float*p1,float*out){for(int j=0;j<FRAME;j++){float r=0;for(int b=0;b<C3B;b++)r+=c->w[b][ca->a[b][j]];out[j]=p1[j]+r/C3B;if(out[j]<.001f)out[j]=.001f;if(out[j]>.999f)out[j]=.999f;}}
static void c3train(C3Cube*c,const C3Cache*ca,const float*p1,const uint8_t*t){float p[FRAME];c3pred(c,ca,p1,p);for(int j=0;j<FRAME;j++){float e=(float)t[j]-p[j],d=.20f*e/C3B;for(int b=0;b<C3B;b++){float*w=&c->w[b][ca->a[b][j]];*w+=d;if(*w>1.5f)*w=1.5f;if(*w<-1.5f)*w=-1.5f;c->writes++;}}}
static void eval_hier(const FC*fc,const QC*q1,const F2Cube*f2c,const C3Cube*c3,int N,uint64_t seed,int mode,const char*tag){RNG r={seed};Game g;init(&g,ri(&r,7));Pilot po={0};uint8_t a[FRAME],t[FRAME];float fun[FD],p1[FRAME],p2[FRAME],f2[F2D];Cache c1;C3Cache c3c;M m={0};for(int i=0;i<N;i++){if(g.game_over){init(&g,ri(&r,7));memset(&po,0,sizeof(po));}render(&g,a);int ac=pol(&g,&po,&r,1);int ev=step(&g,ac);render(&g,t);fw(fc,ac,fun);cache(a,fun,&c1);predq(q1,&c1,a,fun,p1);uint32_t ad[F2B];f2addrs(a,p1,fun,ad);f2pred(f2c,ad,f2);if(mode==1)memset(f2,0,sizeof(f2));else if(mode==2)for(int k=0;k<F2D;k++)f2[k]=-f2[k];else if(mode==3){float z=f2[0];for(int k=0;k<F2D-1;k++)f2[k]=f2[k+1];f2[F2D-1]=z;}c3cache_build(a,p1,f2,&c3c);c3pred(c3,&c3c,p1,p2);madd(&m,a,t,p2,ev);}mp(tag,&m);}
#define XB 27
#define XBITS 22
#define XSZ (1u<<XBITS)
#define XMASK (XSZ-1u)
typedef struct{float*w;unsigned long long writes;}CrossCube;
static void xinit(CrossCube*x){memset(x,0,sizeof(*x));x->w=calloc(XSZ,sizeof(float));if(!x->w)exit(2);}
static void xfree(CrossCube*x){free(x->w);}
static uint16_t blockpat(const uint8_t*f,int b){uint16_t p=0;int base=b*16;for(int k=0;k<16;k++){int j=base+k;if(j<FRAME&&f[j])p|=(uint16_t)(1u<<k);}return p;}
static uint32_t stage_sig(const float*f2,const uint8_t*f,const float*fun){uint32_t cq=(uint32_t)(compat_wave13(f,fun)*15.999f);uint32_t h=cq*0x9e3779b9u;for(int r=0;r<4;r++){double z=0;for(int k=0;k<F2D;k++)z+=((mix((uint32_t)(k*313+r*977+17))&1u)?1.:-1.)*f2[k];h=mix(h^((uint32_t)(z>0)+0x100u*(r+1)));}return h;}
static uint32_t xa(uint32_t sig,int b,uint16_t pat,int out){return mix(sig^mix((uint32_t)(b+1)*0x85ebca6bu)^mix((uint32_t)pat+0x10001u*(uint32_t)(out+1)))&XMASK;}
static void xpred(const CrossCube*x,const uint8_t*f,const float*fun,const float*f2,const float*p2,float*out){memcpy(out,p2,sizeof(float)*FRAME);uint32_t sig=stage_sig(f2,f,fun);const float sc=1.f/sqrtf((float)XB);for(int j=CELLS;j<416;j++){float z=0;for(int b=0;b<XB;b++)z+=x->w[xa(sig,b,blockpat(f,b),j)];out[j]+=z*sc;if(out[j]<.001f)out[j]=.001f;if(out[j]>.999f)out[j]=.999f;}}
static void xtrain(CrossCube*x,const uint8_t*f,const float*fun,const float*f2,const float*p2,const uint8_t*t){float p[FRAME];xpred(x,f,fun,f2,p2,p);uint32_t sig=stage_sig(f2,f,fun);const float sc=1.f/sqrtf((float)XB);for(int j=CELLS;j<416;j++){float e=(float)t[j]-p[j];if(fabsf(e)<.02f)continue;float d=.12f*e*sc;for(int b=0;b<XB;b++){float*w=&x->w[xa(sig,b,blockpat(f,b),j)];*w+=d;if(*w>2.f)*w=2.f;if(*w<-2.f)*w=-2.f;x->writes++;}}}
static void eval_cross(const FC*fc,const QC*q1,const F2Cube*f2c,const C3Cube*c3,const CrossCube*x,int N,uint64_t seed,int off,const char*tag){RNG r={seed};Game g;init(&g,ri(&r,7));Pilot po={0};uint8_t a[FRAME],t[FRAME];float fun[FD],p1[FRAME],p2[FRAME],p3[FRAME],f2[F2D];Cache c1;C3Cache c3c;M m={0};for(int i=0;i<N;i++){if(g.game_over){init(&g,ri(&r,7));memset(&po,0,sizeof(po));}render(&g,a);int ac=pol(&g,&po,&r,1);int ev=step(&g,ac);render(&g,t);fw(fc,ac,fun);cache(a,fun,&c1);predq(q1,&c1,a,fun,p1);uint32_t ad[F2B];f2addrs(a,p1,fun,ad);f2pred(f2c,ad,f2);c3cache_build(a,p1,f2,&c3c);c3pred(c3,&c3c,p1,p2);if(off)memcpy(p3,p2,sizeof(p3));else xpred(x,a,fun,f2,p2,p3);madd(&m,a,t,p3,ev);}mp(tag,&m);}

int main(int argc,char**argv){int warm=argc>1?atoi(argv[1]):12000,base=argc>2?atoi(argv[2]):120000,hier=argc>3?atoi(argv[3]):120000,crossn=argc>4?atoi(argv[4]):120000,evn=argc>5?atoi(argv[5]):5000;FC fc={0};QC q1;qi(&q1);RNG r={0x1234567};Game g;init(&g,ri(&r,7));Pilot po={0};uint8_t a[FRAME],t[FRAME];for(int i=0;i<warm;i++){if(g.game_over){init(&g,ri(&r,7));memset(&po,0,sizeof(po));}render(&g,a);int ac=pol(&g,&po,&r,1);step(&g,ac);render(&g,t);fobs(&fc,a,ac,t);}for(int i=0;i<base;i++){if(g.game_over){init(&g,ri(&r,7));memset(&po,0,sizeof(po));}render(&g,a);int ac=pol(&g,&po,&r,1);step(&g,ac);render(&g,t);float fun[FD];Cache c;fw(&fc,ac,fun);cache(a,fun,&c);trainq(&q1,&c,a,fun,t);}F2Cube f2c;f2init(&f2c);C3Cube c3;c3init(&c3);for(int i=0;i<hier;i++){if(g.game_over){init(&g,ri(&r,7));memset(&po,0,sizeof(po));}render(&g,a);int ac=pol(&g,&po,&r,1);step(&g,ac);render(&g,t);float fun[FD],p1[FRAME],rt[F2D],f2[F2D];Cache c1;fw(&fc,ac,fun);cache(a,fun,&c1);predq(&q1,&c1,a,fun,p1);uint32_t ad[F2B];f2addrs(a,p1,fun,ad);f2pred(&f2c,ad,f2);C3Cache c3c;c3cache_build(a,p1,f2,&c3c);c3train(&c3,&c3c,p1,t);residual_target(a,p1,t,rt);f2train(&f2c,ad,rt);}printf("v0.14b anonymous-block cross relation warm=%d base=%d hier=%d cross=%d\n",warm,base,hier,crossn);eval_hier(&fc,&q1,&f2c,&c3,evn,0x140001u,0,"pre-cross");CrossCube x;xinit(&x);for(int i=0;i<crossn;i++){if(g.game_over){init(&g,ri(&r,7));memset(&po,0,sizeof(po));}render(&g,a);int ac=pol(&g,&po,&r,1);step(&g,ac);render(&g,t);float fun[FD],p1[FRAME],p2[FRAME],f2[F2D];Cache c1;C3Cache cc;fw(&fc,ac,fun);cache(a,fun,&c1);predq(&q1,&c1,a,fun,p1);uint32_t ad[F2B];f2addrs(a,p1,fun,ad);f2pred(&f2c,ad,f2);c3cache_build(a,p1,f2,&cc);c3pred(&c3,&cc,p1,p2);xtrain(&x,a,fun,f2,p2,t);if((i+1)%30000==0){char tag[32];snprintf(tag,sizeof(tag),"cross@%d",i+1);eval_cross(&fc,&q1,&f2c,&c3,&x,2000,0x140100u+(uint64_t)i,0,tag);}}
eval_cross(&fc,&q1,&f2c,&c3,&x,evn,0x14F1A1u,0,"cross-final");eval_cross(&fc,&q1,&f2c,&c3,&x,evn,0x14F1A1u,1,"cross-off");printf("writes F2=%llu C3=%llu Cross=%llu\n",f2c.writes,c3.writes,x.writes);xfree(&x);c3free(&c3);f2free(&f2c);qf(&q1);return 0;}
