#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

enum{A0=0,A1=1,A2=2,A3=3,NA=4};static const int DX[NA]={0,0,-1,1},DY[NA]={-1,1,0,0};
typedef struct{uint32_t z[NA][3][3],o[NA][3][3];}Move;
typedef struct{float sum[NA][9][9];uint32_t n[NA][9][9];}Pair;
typedef struct{uint64_t s;}RNG;static uint32_t ru(RNG*r){r->s^=r->s>>12;r->s^=r->s<<25;r->s^=r->s>>27;return(uint32_t)((r->s*2685821657736338717ULL)>>32);}static int ri(RNG*r,int n){return n?(int)(ru(r)%(uint32_t)n):0;}
static int reality(const uint8_t*m,const uint8_t*w,uint8_t*out,int W,int H,int a,int rigid){memcpy(out,m,(size_t)W*H);int blocked=0;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(m[y*W+x]){int nx=x+DX[a],ny=y+DY[a];if(nx<0||nx>=W||ny<0||ny>=H||w[ny*W+nx])blocked=1;}if(rigid&&blocked)return 1;memset(out,0,(size_t)W*H);for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(m[y*W+x]){int nx=x+DX[a],ny=y+DY[a];if(nx<0||nx>=W||ny<0||ny>=H||w[ny*W+nx])out[y*W+x]=1;else out[ny*W+nx]=1;}return 1;}
static void train_move(Move*b,int epochs){uint8_t in[9],w[9]={0},t[9];for(int e=0;e<epochs;e++)for(int a=0;a<NA;a++)for(int pos=0;pos<9;pos++){memset(in,0,9);in[pos]=1;int x=pos%3,y=pos/3,nx=x+DX[a],ny=y+DY[a];if(nx<0||nx>=3||ny<0||ny>=3)continue;reality(in,w,t,3,3,a,1);for(int oy=0;oy<3;oy++)for(int ox=0;ox<3;ox++)for(int dy=-1;dy<=1;dy++)for(int dx=-1;dx<=1;dx++){int sx=ox+dx,sy=oy+dy;if(sx<0||sx>=3||sy<0||sy>=3||!in[sy*3+sx])continue;uint32_t*p=t[oy*3+ox]?&b->o[a][dy+1][dx+1]:&b->z[a][dy+1][dx+1];(*p)++;}}}
static float tp(const Move*b,int a,int dy,int dx){uint32_t z=b->z[a][dy+1][dx+1],o=b->o[a][dy+1][dx+1];return((float)o+.5f)/((float)(z+o)+1.f);}
static float basep(const Move*b,const uint8_t*m,int W,int H,int a,int ox,int oy){double miss=1;int any=0;for(int dy=-1;dy<=1;dy++)for(int dx=-1;dx<=1;dx++){int x=ox+dx,y=oy+dy;if(x<0||x>=W||y<0||y>=H||!m[y*W+x])continue;any=1;miss*=1.0-tp(b,a,dy,dx);}return any?(float)(1.0-miss):0.f;}
static void train_pair(const Move*b,Pair*p,const uint8_t*m,const uint8_t*w,const uint8_t*t,int W,int H,int a){for(int oy=0;oy<H;oy++)for(int ox=0;ox<W;ox++){float e=(float)t[oy*W+ox]-basep(b,m,W,H,a,ox,oy);for(int mdy=-1;mdy<=1;mdy++)for(int mdx=-1;mdx<=1;mdx++){int mx=ox+mdx,my=oy+mdy;if(mx<0||mx>=W||my<0||my>=H||!m[my*W+mx])continue;int mi=(mdy+1)*3+mdx+1;for(int wdy=-1;wdy<=1;wdy++)for(int wdx=-1;wdx<=1;wdx++){int wx=ox+wdx,wy=oy+wdy;if(wx<0||wx>=W||wy<0||wy>=H||!w[wy*W+wx])continue;int wi=(wdy+1)*3+wdx+1;p->sum[a][mi][wi]+=e;p->n[a][mi][wi]++;}}}}
static void rand_single(RNG*r,uint8_t*m,uint8_t*w,int W,int H,int a){for(;;){memset(m,0,(size_t)W*H);memset(w,0,(size_t)W*H);int x=ri(r,W),y=ri(r,H),nx=x+DX[a],ny=y+DY[a];if(nx<0||nx>=W||ny<0||ny>=H)continue;m[y*W+x]=1;int mode=ri(r,2);if(mode)w[ny*W+nx]=1;else{for(int z=0;z<100;z++){int wx=ri(r,W),wy=ri(r,H);if((wx!=x||wy!=y)&&(wx!=nx||wy!=ny)){w[wy*W+wx]=1;break;}}}return;}}
static void train3(const Move*b,Pair*p,int epochs){RNG r={7};uint8_t m[9],w[9],t[9];for(int e=0;e<epochs;e++)for(int a=0;a<NA;a++)for(int k=0;k<64;k++){rand_single(&r,m,w,3,3,a);reality(m,w,t,3,3,a,1);train_pair(b,p,m,w,t,3,3,a);}}
static float cell_go(const Move*b,const Pair*p,const uint8_t*m,const uint8_t*w,int W,int H,int a,int x,int y){(void)m;int nx=x+DX[a],ny=y+DY[a];if(nx<0||nx>=W||ny<0||ny>=H)return 0.f;int mdx=x-nx,mdy=y-ny,mi=(mdy+1)*3+mdx+1;float q=tp(b,a,mdy,mdx);for(int wdy=-1;wdy<=1;wdy++)for(int wdx=-1;wdx<=1;wdx++){int wx=nx+wdx,wy=ny+wdy;if(wx<0||wx>=W||wy<0||wy>=H||!w[wy*W+wx])continue;int wi=(wdy+1)*3+wdx+1;if(p->n[a][mi][wi])q+=p->sum[a][mi][wi]/p->n[a][mi][wi];}if(q<0)q=0;if(q>1)q=1;return q;}
static void predict_shared(const Move*b,const Pair*p,const uint8_t*m,const uint8_t*w,uint8_t*out,int W,int H,int a,int ablate){float C=1.f;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(m[y*W+x])C*=cell_go(b,p,m,w,W,H,a,x,y);if(ablate==1)C=1.f;else if(ablate==2)C=1.f-C;for(int y=0;y<H;y++)for(int x=0;x<W;x++){float moved=basep(b,m,W,H,a,x,y),stay=(float)m[y*W+x];float q=C*moved+(1.f-C)*stay;out[y*W+x]=(uint8_t)(q>.5f);}}
static int make_world(RNG*r,uint8_t*m,uint8_t*w,int W,int H){static const uint16_t TS[7][4]={{0x00F0,0x4444,0x00F0,0x4444},{0x0660,0x0660,0x0660,0x0660},{0x0270,0x0262,0x0720,0x0232},{0x0360,0x0462,0x0360,0x0462},{0x0630,0x0264,0x0630,0x0264},{0x0710,0x0226,0x0470,0x0322},{0x0740,0x0622,0x0170,0x0223}};memset(m,0,(size_t)W*H);memset(w,0,(size_t)W*H);for(int x=0;x<W;x++)w[(H-1)*W+x]=1;for(int k=0;k<20;k++){int x=ri(r,W),y=H-2-ri(r,6);w[y*W+x]=1;}for(int q=0;q<300;q++){int ty=ri(r,7),rot=ri(r,4),x=ri(r,W+4)-2,y=ri(r,3)-1;uint16_t mm=TS[ty][rot];int ok=1,n=0,c[4][2];for(int sy=0;sy<4;sy++)for(int sx=0;sx<4;sx++)if((mm>>(sy*4+sx))&1){int xx=x+sx,yy=y+sy;if(xx<0||xx>=W||yy<0||yy>=H||w[yy*W+xx])ok=0;if(n<4){c[n][0]=xx;c[n][1]=yy;}n++;}if(!ok||n!=4)continue;for(int k=0;k<4;k++)m[c[k][1]*W+c[k][0]]=1;return 1;}return 0;}
static int step_real(const uint8_t*m,const uint8_t*w,uint8_t*out,int W,int H){return reality(m,w,out,W,H,A1,1);}
static int same(const uint8_t*a,const uint8_t*b,int n){return memcmp(a,b,(size_t)n)==0;}
static int hard_real(const uint8_t*m,const uint8_t*w,uint8_t*out,int W,int H){uint8_t*a=malloc(W*H),*b=malloc(W*H);memcpy(a,m,(size_t)W*H);int n=0;for(;n<64;n++){step_real(a,w,b,W,H);if(same(a,b,W*H))break;memcpy(a,b,(size_t)W*H);}memcpy(out,a,(size_t)W*H);free(a);free(b);return n;}
static int hard_model(const Move*b,const Pair*p,const uint8_t*m,const uint8_t*w,uint8_t*out,int W,int H,int ablate){uint8_t*a=malloc(W*H),*nx=malloc(W*H);memcpy(a,m,(size_t)W*H);int n=0;for(;n<64;n++){predict_shared(b,p,a,w,nx,W,H,A1,ablate);if(same(a,nx,W*H))break;memcpy(a,nx,(size_t)W*H);}memcpy(out,a,(size_t)W*H);free(a);free(nx);return n;}
static void audit(const Move*b,const Pair*p,int N,uint64_t seed,int ablate){int W=10,H=20;RNG r={seed};uint8_t*m=malloc(W*H),*w=malloc(W*H),*tr=malloc(W*H),*pm=malloc(W*H);unsigned long long exactn=0,stepok=0;double dh=0,dm=0;for(int i=0;i<N;i++){if(!make_world(&r,m,w,W,H)){i--;continue;}int hr=hard_real(m,w,tr,W,H),hm=hard_model(b,p,m,w,pm,W,H,ablate);exactn+=same(tr,pm,W*H);stepok+=(hr==hm);dh+=hr;dm+=hm;}const char*nm=ablate==0?"normal":"carrier-off";printf("%-16s n=%d final_exact=%7.3f%% step_exact=%7.3f%% true_h=%.2f model_h=%.2f\n",nm,N,100.0*exactn/N,100.0*stepok/N,dh/N,dm/N);free(m);free(w);free(tr);free(pm);}
int main(){Move b={0};Pair p={0};train_move(&b,30);train3(&b,&p,100);puts("BPC Tetris Minimal v0.6d terrain recursive hard-drop | no hard-drop training");audit(&b,&p,10000,123,0);audit(&b,&p,10000,123,1);return 0;}
