/* Test harness: the model receives its own predicted frame at every next tick.
   Only a fresh external Preview is injected after a successful real Lock; no
   board, hidden trace, real next-frame pointer or evaluation learning is fed in. */
#ifndef CORE
#define CORE "model.c"
#endif
#include CORE
#include <time.h>
static uint64_t audit_hash(const void*p,size_t n){const unsigned char*b=p;uint64_t h=1469598103934665603ULL;for(size_t i=0;i<n;i++){h^=b[i];h*=1099511628211ULL;}return h;}
static void train_frozen(SharedField*f){sf_train_all_direct(f);for(int i=0;i<4;i++)sf_train_closure_from_slow_play(f,250,0x380038ULL+0x101ULL*(uint64_t)i,i%2);sf_reset_split_evidence(f);sf_train_split_from_visible_play(f,2500,0x390039ULL);sf_train_life_direct(f,40000);printf("TRAINED relations=%d hash=%016llx\n",f->n,(unsigned long long)audit_hash(f,sizeof(*f)));}
typedef struct{unsigned long long n,ok,trace,locks,over;int first_ep,first_t,first_act;}AuditStat;
/* The existing external player only generates test operations. Its search and
   board heuristic never reach sf_binary_step or the probability field. */
static int autoplay(SharedField*f,int pieces,uint64_t seed){RNG r={seed};State real;init_episode(&r,&real);BinaryState model;RawFrame empty={{0}};render_raw(&real,&model.frame);trace_birth(&empty,&model.frame,model.trace);unsigned long long actions=0,ok=0,events=0,lines=0,four=0,overs=0;for(int pi=0;pi<pieces;pi++){if(real.gameover){init_episode(&r,&real);render_raw(&real,&model.frame);trace_birth(&empty,&model.frame,model.trace);}LearnPlan plan=lp_choose(&real);for(int j=0;j<plan.n;j++){int wb=lp_bits(real.world),ab=lp_bits(real.active),act=plan.a[j];int lr=real_step(&real,act);ActionWave wave=opwave(act);int lm=sf_binary_step(f,&model,&wave);RawFrame truth;render_raw(&real,&truth);int same=lr==lm&&raw_eq(&truth,&model.frame)&&eq(real.active,model.trace,N);actions++;ok+=same;if(!same){printf("AUTOPLAY seed=%llu pieces=%d exact=%llu/%llu first_piece=%d action=%d\n",(unsigned long long)seed,pieces,ok,actions,pi,act);return 0;}if(lr){int removed=wb+ab-lp_bits(real.world),clears=removed>0?removed/W:0;events+=clears>0;lines+=(unsigned long long)clears;four+=clears==4;overs+=real.gameover;if(!real.gameover){uint8_t p[PREV];preview_shape(ri(&r,7),p);memcpy(real.preview,p,PREV);for(int y=0;y<4;y++)for(int x=0;x<4;x++)model.frame.px[ridx(11+x,y)]=p[y*4+x];}break;}}}printf("AUTOPLAY seed=%llu pieces=%d exact=%llu/%llu clear_events=%llu lines=%llu four=%llu gameovers=%llu\n",(unsigned long long)seed,pieces,ok,actions,events,lines,four,overs);return ok==actions;}
static AuditStat strict_rollout(SharedField*f,int eps,int horizon,uint64_t seed,int mode){RNG r={seed};AuditStat z={0};z.first_ep=z.first_t=z.first_act=-1;SharedField saved=*f;if(mode==1)memset(f,0,sizeof(*f));for(int ep=0;ep<eps;ep++){State real;init_episode(&r,&real);BinaryState model;RawFrame empty={{0}},initial;render_raw(&real,&initial);model.frame=initial;trace_birth(&empty,&initial,model.trace);if(mode==3)memset(model.trace,0,N);for(int t=0;t<horizon;t++){int u=ri(&r,100),act=u<18?0:u<36?1:u<50?3:u<70?2:4;int lr=real_step(&real,act);RawFrame truth;render_raw(&real,&truth);ActionWave wave=opwave(mode==2?(act+1)%ACTS:act);int lm=sf_binary_step(f,&model,&wave),same=(lr==lm)&&raw_eq(&truth,&model.frame);z.n++;z.ok+=same;z.trace+=!memcmp(real.active,model.trace,N);z.locks+=!!lr;z.over+=!!real.gameover;if(!same){if(z.first_ep<0){z.first_ep=ep;z.first_t=t;z.first_act=act;}break;}if(lr){if(real.gameover)break;uint8_t p[PREV];preview_shape(ri(&r,7),p);memcpy(real.preview,p,PREV);for(int y=0;y<4;y++)for(int x=0;x<4;x++)model.frame.px[ridx(11+x,y)]=p[y*4+x];}}}if(mode==1)*f=saved;return z;}
static int clear_suite(SharedField*f,int per,int negative,uint64_t seed){RNG r={seed};unsigned long long ok=0,total=0;for(int k=1;k<=4;k++)for(int q=0;q<per;q++){uint8_t a[N]={0},b[N]={0};for(int y=0;y<H-k;y++){int ones=0;for(int x=0;x<W;x++){a[y*W+x]=(uint8_t)(ri(&r,100)<28);ones+=a[y*W+x];}if(ones==W)a[y*W+ri(&r,W)]=0;}for(int y=H-k;y<H;y++)for(int x=0;x<W;x++)a[y*W+x]=1;memcpy(b,a,N);real_clear(a);int guard=0;while(sf_clear_relation(f,b)&&guard++<H*4){}ok+=eq(a,b,N);total++;}printf("CLEAR_STRESS %llu/%llu\n",ok,total);int pass=ok==total;ok=0;for(int q=0;q<negative;q++){uint8_t a[N]={0},b[N]={0};int col=ri(&r,W);for(int y=0;y<H;y++){for(int x=0;x<W;x++)if(x!=col)a[y*W+x]=(uint8_t)(ri(&r,100)<12);a[y*W+col]=1;int x=ri(&r,W-1);if(x>=col)x++;a[y*W+x]=0;}memcpy(b,a,N);real_clear(a);(void)sf_clear_relation(f,b);ok+=eq(a,b,N);}printf("VERTICAL_NONCLEAR %llu/%d\n",ok,negative);return pass&&ok==(unsigned long long)negative;}
/* Validation only: full rows may occur at any distinct addresses, with arbitrary
   gaps and partial rows between them. No generated test frame enters training. */
static int gap_suite(SharedField*f,int per,uint64_t seed){RNG r={seed};int pass=1;unsigned long long ok=0,total=0;for(int k=1;k<=4;k++){int good=0;for(int q=0;q<per;q++){uint8_t a[N]={0},b[N],selected[H]={0};for(int j=0;j<k;j++){int y;do{y=ri(&r,H);}while(selected[y]);selected[y]=1;}for(int y=0;y<H;y++){int n=0;for(int x=0;x<W;x++){a[y*W+x]=(uint8_t)(selected[y]||ri(&r,100)<28);n+=a[y*W+x];}if(!selected[y]&&n==W)a[y*W+ri(&r,W)]=0;}memcpy(b,a,N);real_clear(a);int guard=0;while(sf_clear_relation(f,b)&&guard++<H*4){}good+=eq(a,b,N);}printf("ARBITRARY_CLEAR k%d %d/%d\n",k,good,per);pass&=good==per;ok+=(unsigned long long)good;total+=(unsigned long long)per;}printf("ARBITRARY_TOTAL %llu/%llu\n",ok,total);return pass;}

int main(int argc,char**argv){setbuf(stdout,NULL);if(argc<3){fprintf(stderr,"usage: audit train|eval|controls|autoplay FIELD [first_seed count episodes clear_per negative horizon]\n");return 2;}SharedField f={0};clock_t start=clock();if(!strcmp(argv[1],"train")){train_frozen(&f);FILE*p=fopen(argv[2],"wb");if(!p||fwrite(&f,sizeof(f),1,p)!=1)return 3;fclose(p);return 0;}FILE*p=fopen(argv[2],"rb");if(!p||fread(&f,sizeof(f),1,p)!=1)return 3;fclose(p);SharedField saved=f;int pass=1;if(!strcmp(argv[1],"eval")){int first=argc>3?atoi(argv[3]):0,count=argc>4?atoi(argv[4]):8,eps=argc>5?atoi(argv[5]):1000,per=argc>6?atoi(argv[6]):2500,neg=argc>7?atoi(argv[7]):2500,horizon=argc>8?atoi(argv[8]):120;if(per||neg)pass&=clear_suite(&f,per,neg,0xC1EAULL);unsigned long long ok=0,n=0;for(int s=first;s<first+count;s++){AuditStat z=strict_rollout(&f,eps,horizon,98765ULL+200003ULL*(uint64_t)s,0);printf("SEED%d %llu/%llu trace=%llu locks=%llu gameovers=%llu first=%d:%d:%d\n",s,z.ok,z.n,z.trace,z.locks,z.over,z.first_ep,z.first_t,z.first_act);ok+=z.ok;n+=z.n;pass&=z.ok==z.n&&z.trace==z.n;}printf("TOTAL %llu/%llu\n",ok,n);}else if(!strcmp(argv[1],"gap")){pass&=gap_suite(&f,argc>3?atoi(argv[3]):2500,0x460046ULL);}else if(!strcmp(argv[1],"controls")){for(int m=0;m<4;m++){AuditStat z=strict_rollout(&f,100,120,20261006ULL,m);printf("CONTROL%d %llu/%llu first=%d:%d:%d\n",m,z.ok,z.n,z.first_ep,z.first_t,z.first_act);pass&=m==0?z.ok==z.n:z.ok<z.n;}}else if(!strcmp(argv[1],"autoplay")){int pieces=argc>3?atoi(argv[3]):1000,count=argc>4?atoi(argv[4]):5;uint64_t first=argc>5?strtoull(argv[5],NULL,10):20261010ULL;for(int s=0;s<count;s++)pass&=autoplay(&f,pieces,first+(uint64_t)s);}else return 2;int frozen=!memcmp(&f,&saved,sizeof(f));pass&=frozen;printf("FROZEN_BYTE_IDENTICAL=%d hash=%016llx PASS=%d CPU_SECONDS=%.3f\n",frozen,(unsigned long long)audit_hash(&f,sizeof(f)),pass,(double)(clock()-start)/CLOCKS_PER_SEC);return pass?0:1;}
