/* The environment supplies initial pixels and a fresh external Preview.
   Every next step uses the model's own predicted board and trace. No real
   next-frame replacement, oracle plan, hidden mid-clear board or reward. */
#include "model.c"
#include <time.h>
static uint64_t audit_hash(const void*p,size_t n){const unsigned char*b=p;uint64_t h=1469598103934665603ULL;for(size_t i=0;i<n;i++){h^=b[i];h*=1099511628211ULL;}return h;}
typedef struct{unsigned long long n,ok,trace,locks,over;int first_ep,first_t,first_act;}AuditStat;
static AuditStat strict_rollout(SharedField*f,int eps,int horizon,uint64_t seed,int mode){RNG r={seed};AuditStat z={0};z.first_ep=z.first_t=z.first_act=-1;SharedField saved=*f;if(mode==1)memset(f,0,sizeof(*f));for(int ep=0;ep<eps;ep++){State real;init_episode(&r,&real);BinaryState model;RawFrame empty={{0}},initial;render_raw(&real,&initial);model.frame=initial;trace_birth(&empty,&initial,model.trace);if(mode==3)memset(model.trace,0,N);for(int t=0;t<horizon;t++){int u=ri(&r,100),act=u<18?0:u<36?1:u<50?3:u<70?2:4;int lr=real_step(&real,act);RawFrame truth;render_raw(&real,&truth);ActionWave wave=opwave(mode==2?(act+1)%ACTS:act);int lm=sf_binary_step(f,&model,&wave),same=(lr==lm)&&raw_eq(&truth,&model.frame);z.n++;z.ok+=same;z.trace+=!memcmp(real.active,model.trace,N);z.locks+=!!lr;z.over+=!!real.gameover;if(!same){if(z.first_ep<0){z.first_ep=ep;z.first_t=t;z.first_act=act;}break;}if(lr){if(real.gameover)break;uint8_t p[PREV];preview_shape(ri(&r,7),p);memcpy(real.preview,p,PREV);for(int y=0;y<4;y++)for(int x=0;x<4;x++)model.frame.px[ridx(11+x,y)]=p[y*4+x];}}}if(mode==1)*f=saved;return z;}
static int clear_suite(SharedField*f,int per,int negative,uint64_t seed){RNG r={seed};unsigned long long ok=0,total=0;for(int k=1;k<=4;k++)for(int q=0;q<per;q++){uint8_t a[N]={0},b[N]={0};for(int y=0;y<H-k;y++){int ones=0;for(int x=0;x<W;x++){a[y*W+x]=(uint8_t)(ri(&r,100)<28);ones+=a[y*W+x];}if(ones==W)a[y*W+ri(&r,W)]=0;}for(int y=H-k;y<H;y++)for(int x=0;x<W;x++)a[y*W+x]=1;memcpy(b,a,N);real_clear(a);int guard=0;while(sf_clear_relation(f,b)&&guard++<H*4){}ok+=eq(a,b,N);total++;}printf("CLEAR_STRESS %llu/%llu\n",ok,total);int pass=ok==total;ok=0;for(int q=0;q<negative;q++){uint8_t a[N]={0},b[N]={0};int col=ri(&r,W);for(int y=0;y<H;y++){for(int x=0;x<W;x++)if(x!=col)a[y*W+x]=(uint8_t)(ri(&r,100)<12);a[y*W+col]=1;int x=ri(&r,W-1);if(x>=col)x++;a[y*W+x]=0;}memcpy(b,a,N);real_clear(a);(void)sf_clear_relation(f,b);ok+=eq(a,b,N);}printf("VERTICAL_NONCLEAR %llu/%d\n",ok,negative);return pass&&ok==(unsigned long long)negative;}
/* Validation only: full rows may occur at any distinct addresses, with arbitrary
   gaps and partial rows between them. No generated test frame enters training. */
static int gap_suite(SharedField*f,int per,uint64_t seed){RNG r={seed};int pass=1;unsigned long long ok=0,total=0;for(int k=1;k<=4;k++){int good=0;for(int q=0;q<per;q++){uint8_t a[N]={0},b[N],selected[H]={0};for(int j=0;j<k;j++){int y;do{y=ri(&r,H);}while(selected[y]);selected[y]=1;}for(int y=0;y<H;y++){int n=0;for(int x=0;x<W;x++){a[y*W+x]=(uint8_t)(selected[y]||ri(&r,100)<28);n+=a[y*W+x];}if(!selected[y]&&n==W)a[y*W+ri(&r,W)]=0;}memcpy(b,a,N);real_clear(a);int guard=0;while(sf_clear_relation(f,b)&&guard++<H*4){}good+=eq(a,b,N);}printf("ARBITRARY_CLEAR k%d %d/%d\n",k,good,per);pass&=good==per;ok+=(unsigned long long)good;total+=(unsigned long long)per;}printf("ARBITRARY_TOTAL %llu/%llu\n",ok,total);return pass;}

/* The anonymous tapes are hand-written. Choice is independent of the screen.
   Training emits the final channel as repeated one-step pulses to observe
   actual transitions, rather than fabricating a pre-clear teaching board. */
static const char*tapes[]={"000004","111114","0004","114","333000004","311114","33004","333114","4","304","314","3304","3314","33304","33314","0003334","111334"};
static void camera(const uint8_t*src,uint8_t*dst,int reflect){for(int y=0;y<H;y++)for(int x=0;x<W;x++)dst[(reflect?H-1-y:y)*W+x]=src[y*W+x];}
static int settle(SharedField*f,uint8_t*b,double vx,double vy){int c=0;while(sf_transport_vector(f,b,vx,vy)&&c++<H*4){}return c<H*4;}
/* Each physical intervention receives an ordinary Bernoulli observation:
   did its predicted consequence equal the actual observed consequence?
   All four get credit. There is no winner, reward, distance or ranking. */
static int observe(SharedField*f,const State*before,int act,const State*truth,int reflect){State mid;sf_mid(f,before,act,&mid);if(eq(mid.world,truth->world,N))return 0;uint8_t b[N],t[N];camera(mid.world,b,reflect);camera(truth->world,t,reflect);int dx[4],dy[4];physical_dirs(dx,dy);for(int d=0;d<4;d++){uint8_t q[N];memcpy(q,b,N);int stable=settle(f,q,dx[d],dy[d]);sfcredit(f,kdrift(dx[d],dy[d]),1,stable&&eq(q,t,N));}return 1;}
static int learn_direction(SharedField*f,int pieces,uint64_t seed,int reflect){RNG r={seed};State real;init_episode(&r,&real);int events=0,actions=0;for(int pi=0;pi<pieces;pi++){if(real.gameover)init_episode(&r,&real);const char*p=tapes[ri(&r,(int)(sizeof(tapes)/sizeof(*tapes)))];int locked=0;for(int j=0;p[j]&&!locked;j++){int a=p[j]-'0',repeat=a==ACT_DROP?64:1;for(int t=0;t<repeat&&!locked;t++){int act=a==ACT_DROP?ACT_DOWN:a;State before=real,truth=real;locked=real_step(&truth,act);events+=observe(f,&before,act,&truth,reflect);real=truth;actions++;}}if(locked&&!real.gameover){uint8_t np[PREV];preview_shape(ri(&r,7),np);memcpy(real.preview,np,PREV);}}int dx[4],dy[4];physical_dirs(dx,dy);printf("LEARN seed=%llu pieces=%d actions=%d residual_events=%d camera_reflect=%d\n",(unsigned long long)seed,pieces,actions,events,reflect);for(int d=0;d<4;d++){SFCell*e=sffind(f,kdrift(dx[d],dy[d]),0);printf("DIRECTION %d,%d yes=%.0f total=%.0f p=%.9f\n",dx[d],dy[d],e?e->yes:0,e?e->total:0,sfget(f,kdrift(dx[d],dy[d]),.5));}double vx,vy;sf_drift(f,&vx,&vy);printf("DRIFT %.9f,%.9f\n",vx,vy);return events>0;}
/* Test operations come from the same hand-written source, with new seeds.
   No learning occurs; the field is byte-checked after each complete run. */
static int play(SharedField*f,int pieces,uint64_t seed){RNG r={seed};State real;init_episode(&r,&real);BinaryState model;RawFrame empty={{0}};render_raw(&real,&model.frame);trace_birth(&empty,&model.frame,model.trace);unsigned long long n=0,ok=0,events=0,lines=0,four=0,over=0;for(int pi=0;pi<pieces;pi++){if(real.gameover){init_episode(&r,&real);render_raw(&real,&model.frame);trace_birth(&empty,&model.frame,model.trace);}const char*p=tapes[ri(&r,(int)(sizeof(tapes)/sizeof(*tapes)))];for(int j=0;p[j];j++){int act=p[j]-'0',mass=0;for(int i=0;i<N;i++)mass+=!!real.world[i]+!!real.active[i];int lr=real_step(&real,act);ActionWave w=opwave(act);int lm=sf_binary_step(f,&model,&w);RawFrame truth;render_raw(&real,&truth);int same=lr==lm&&raw_eq(&truth,&model.frame)&&eq(real.active,model.trace,N);n++;ok+=same;if(!same){printf("PLAY seed=%llu pieces=%d exact=%llu/%llu first_piece=%d action=%d\n",(unsigned long long)seed,pieces,ok,n,pi,act);return 0;}if(lr){int after=0;for(int i=0;i<N;i++)after+=!!real.world[i];int k=(mass-after)/W;events+=k>0;lines+=(unsigned long long)k;four+=k==4;over+=!!real.gameover;if(!real.gameover){uint8_t np[PREV];preview_shape(ri(&r,7),np);memcpy(real.preview,np,PREV);for(int y=0;y<4;y++)for(int x=0;x<4;x++)model.frame.px[ridx(11+x,y)]=np[y*4+x];}break;}}}printf("PLAY seed=%llu pieces=%d exact=%llu/%llu clear_events=%llu lines=%llu four=%llu gameovers=%llu\n",(unsigned long long)seed,pieces,ok,n,events,lines,four,over);return n==ok;}
static int direction_controls(SharedField*f){SharedField saved=*f;int dx[4],dy[4];physical_dirs(dx,dy);int pass=1;for(int mode=0;mode<4;mode++){*f=saved;if(mode)for(int d=0;d<4;d++){SFCell*e=sffind(f,kdrift(dx[d],dy[d]),0);if(!e)return 0;if(mode==1){e->yes=e->total=0;}else{int x=mode==2?dx[d]:dy[d],y=mode==2?-dy[d]:-dx[d];SFCell*q=sffind(&saved,kdrift(x,y),0);if(!q)return 0;e->yes=q->yes;e->total=q->total;}}int exact=clear_suite(f,100,0,0xDC0ULL);printf("DIRECTION_CONTROL%d all_exact=%d\n",mode,exact);pass&=mode==0?exact:!exact;}*f=saved;for(int mode=0;mode<4;mode++){AuditStat z=strict_rollout(f,100,120,20261006ULL,mode);printf("INPUT_CONTROL%d %llu/%llu\n",mode,z.ok,z.n);pass&=mode==0?z.ok==z.n:z.ok<z.n;}return pass;}
/* Reflection is a display transform in the auditor. The core sees only the
   resulting pixels. This checks closure transport, not the whole reflected
   game interface (the old geometry/preview fields are not retrained here). */
static int symmetry_suite(SharedField*f,int per){RNG r={0xFAAAULL};unsigned long long ok=0,n=0;for(int k=1;k<=4;k++)for(int q=0;q<per;q++){uint8_t a[N]={0},b[N],t[N],pick[H]={0};for(int j=0;j<k;j++){int y;do{y=ri(&r,H);}while(pick[y]);pick[y]=1;}for(int y=0;y<H;y++){int count=0;for(int x=0;x<W;x++){a[y*W+x]=(uint8_t)(pick[y]||ri(&r,100)<28);count+=a[y*W+x];}if(!pick[y]&&count==W)a[y*W+ri(&r,W)]=0;}camera(a,b,1);real_clear(a);camera(a,t,1);int guard=0;while(sf_clear_relation(f,b)&&guard++<H*4){}ok+=eq(b,t,N);n++;}printf("REFLECTED_CLOSURE %llu/%llu\n",ok,n);return n==ok;}
int main(int argc,char**argv){setbuf(stdout,NULL);if(argc<3){fprintf(stderr,"usage: audit learn BASE OUT pieces seed reflect | eval FIELD first count episodes per negative horizon | play FIELD pieces count seed | gap FIELD per | controls FIELD | symmetry FIELD per\n");return 2;}SharedField f={0};FILE*p=fopen(argv[2],"rb");if(!p||fread(&f,sizeof(f),1,p)!=1)return 3;fclose(p);SharedField saved=f;clock_t start=clock();int pass=1;if(!strcmp(argv[1],"learn")){if(argc<4)return 2;pass&=learn_direction(&f,argc>4?atoi(argv[4]):5000,argc>5?strtoull(argv[5],NULL,10):0xDA44ULL,argc>6?atoi(argv[6]):0);int unchanged=!memcmp(f.c,saved.c,(size_t)saved.n*sizeof(*f.c));pass&=unchanged;printf("INHERITED_CELLS_BYTE_IDENTICAL=%d relations=%d hash=%016llx PASS=%d\n",unchanged,f.n,(unsigned long long)audit_hash(&f,sizeof(f)),pass);p=fopen(argv[3],"wb");if(!p||fwrite(&f,sizeof(f),1,p)!=1)return 3;fclose(p);return pass?0:1;}if(!strcmp(argv[1],"eval")){int first=argc>3?atoi(argv[3]):0,count=argc>4?atoi(argv[4]):8,eps=argc>5?atoi(argv[5]):1000,per=argc>6?atoi(argv[6]):2500,neg=argc>7?atoi(argv[7]):2500,horizon=argc>8?atoi(argv[8]):120;if(per||neg)pass&=clear_suite(&f,per,neg,0xC1EAULL);unsigned long long ok=0,n=0;for(int s=first;s<first+count;s++){AuditStat z=strict_rollout(&f,eps,horizon,98765ULL+200003ULL*(uint64_t)s,0);printf("SEED%d %llu/%llu trace=%llu locks=%llu gameovers=%llu first=%d:%d:%d\n",s,z.ok,z.n,z.trace,z.locks,z.over,z.first_ep,z.first_t,z.first_act);ok+=z.ok;n+=z.n;pass&=z.ok==z.n&&z.trace==z.n;}printf("TOTAL %llu/%llu\n",ok,n);}else if(!strcmp(argv[1],"gap"))pass&=gap_suite(&f,argc>3?atoi(argv[3]):2500,0x470047ULL);else if(!strcmp(argv[1],"play")){int pieces=argc>3?atoi(argv[3]):10000,count=argc>4?atoi(argv[4]):5;uint64_t seed=argc>5?strtoull(argv[5],NULL,10):20261025ULL;for(int i=0;i<count;i++)pass&=play(&f,pieces,seed+(uint64_t)i);}else if(!strcmp(argv[1],"controls"))pass&=direction_controls(&f);else if(!strcmp(argv[1],"symmetry"))pass&=symmetry_suite(&f,argc>3?atoi(argv[3]):2500);else return 2;int frozen=!memcmp(&f,&saved,sizeof(f));pass&=frozen;printf("FROZEN_BYTE_IDENTICAL=%d hash=%016llx PASS=%d CPU_SECONDS=%.3f\n",frozen,(unsigned long long)audit_hash(&f,sizeof(f)),pass,(double)(clock()-start)/CLOCKS_PER_SEC);return pass?0:1;}
