#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#define W 10
#define H 20
#define N (W*H)
#define R 2
#define D 5
#define SLOTS 25
#define PREV 16
enum{ACT_LEFT=0,ACT_RIGHT=1,ACT_DOWN=2,ACT_ROT=3,ACT_DROP=4,ACTS=5};
static const int MDX[3]={-1,1,0},MDY[3]={0,0,1};
typedef struct{uint64_t s;}RNG;static uint32_t ru(RNG*r){r->s^=r->s>>12;r->s^=r->s<<25;r->s^=r->s>>27;return(uint32_t)((r->s*2685821657736338717ULL)>>32);}static int ri(RNG*r,int n){return n?(int)(ru(r)%(uint32_t)n):0;}
static int eq(const uint8_t*a,const uint8_t*b,int n){return memcmp(a,b,(size_t)n)==0;}
/* ---------- learned translation primitive ---------- */
typedef struct{uint32_t z[3][3][3],o[3][3][3];}Move;typedef struct{float sum[3][9][9];uint32_t n[3][9][9];}MoveBlock;
static void train_move(Move*m,int ep){for(int e=0;e<ep;e++)for(int a=0;a<3;a++)for(int y=0;y<3;y++)for(int x=0;x<3;x++){int nx=x+MDX[a],ny=y+MDY[a];if(nx<0||nx>=3||ny<0||ny>=3)continue;for(int oy=0;oy<3;oy++)for(int ox=0;ox<3;ox++){int dx=x-ox,dy=y-oy;if(dx<-1||dx>1||dy<-1||dy>1)continue;uint32_t*p=(ox==nx&&oy==ny)?&m->o[a][dy+1][dx+1]:&m->z[a][dy+1][dx+1];(*p)++;}}}
static float mp(const Move*m,int a,int dy,int dx){uint32_t z=m->z[a][dy+1][dx+1],o=m->o[a][dy+1][dx+1];return((float)o+.5f)/((float)(z+o)+1.f);}
static void train_mblock(const Move*m,MoveBlock*b,int ep){RNG r={17};for(int e=0;e<ep;e++)for(int a=0;a<3;a++)for(int k=0;k<200;k++){int sx=ri(&r,3),sy=ri(&r,3),tx=sx+MDX[a],ty=sy+MDY[a];if(tx<0||tx>=3||ty<0||ty>=3){k--;continue;}int blocked=ri(&r,2),wx=tx,wy=ty;if(!blocked){int tries=0;do{int dx=ri(&r,3)-1,dy=ri(&r,3)-1;wx=tx+dx;wy=ty+dy;tries++;}while((wx<0||wx>=3||wy<0||wy>=3||(wx==tx&&wy==ty))&&tries<32);if(wx<0||wx>=3||wy<0||wy>=3||(wx==tx&&wy==ty)){k--;continue;}}int mi=(sy-ty+1)*3+(sx-tx+1),wi=(wy-ty+1)*3+(wx-tx+1);float base=mp(m,a,sy-ty,sx-tx),target=blocked?0.f:1.f;b->sum[a][mi][wi]+=target-base;b->n[a][mi][wi]++;}}
static float move_basep(const Move*m,const uint8_t*src,int a,int ox,int oy){double miss=1;int any=0;for(int dy=-1;dy<=1;dy++)for(int dx=-1;dx<=1;dx++){int x=ox+dx,y=oy+dy;if(x<0||x>=W||y<0||y>=H||!src[y*W+x])continue;any=1;miss*=1.0-mp(m,a,dy,dx);}return any?(float)(1.0-miss):0.f;}
static float move_go(const Move*m,const MoveBlock*b,const uint8_t*world,int a,int x,int y){int tx=x+MDX[a],ty=y+MDY[a];if(tx<0||tx>=W||ty<0||ty>=H)return 0.f;int mi=(y-ty+1)*3+(x-tx+1);float q=mp(m,a,y-ty,x-tx);for(int dy=-1;dy<=1;dy++)for(int dx=-1;dx<=1;dx++){int wx=tx+dx,wy=ty+dy;if(wx<0||wx>=W||wy<0||wy>=H||!world[wy*W+wx])continue;int wi=(dy+1)*3+dx+1;if(b->n[a][mi][wi])q+=b->sum[a][mi][wi]/b->n[a][mi][wi];}if(q<0)q=0;if(q>1)q=1;return q;}
static float move_carrier(const Move*m,const MoveBlock*b,const uint8_t*a,const uint8_t*w,int dir){float C=1.f;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(a[y*W+x])C*=move_go(m,b,w,dir,x,y);return C;}
static void shifted_probs(const Move*m,const uint8_t*src,int dir,float*out){for(int y=0;y<H;y++)for(int x=0;x<W;x++)out[y*W+x]=move_basep(m,src,dir,x,y);}
/* ---------- learned rotation primitive around raw pivot carrier ---------- */
typedef struct{uint32_t z[SLOTS][SLOTS],o[SLOTS][SLOTS];}Rot;typedef struct{uint32_t z[SLOTS][SLOTS],o[SLOTS][SLOTS];}RotBlock;
static int lidx(int dx,int dy){return(dy+R)*D+dx+R;}static void lunidx(int i,int*dx,int*dy){*dy=i/D-R;*dx=i%D-R;}static void rr(int sx,int sy,int*ox,int*oy){*ox=-sy;*oy=sx;}
static void train_rot(Rot*r,int ep){for(int e=0;e<ep;e++)for(int si=0;si<SLOTS;si++){int sx,sy,ox,oy;lunidx(si,&sx,&sy);rr(sx,sy,&ox,&oy);int ti=lidx(ox,oy);for(int oi=0;oi<SLOTS;oi++){uint32_t*p=oi==ti?&r->o[si][oi]:&r->z[si][oi];(*p)++;}}}
static float rp(const Rot*r,int si,int oi){uint32_t z=r->z[si][oi],o=r->o[si][oi];return((float)o+.5f)/((float)(z+o)+1.f);}
static float rot_target_base(const Rot*r,int si){int sx,sy,ox,oy;lunidx(si,&sx,&sy);rr(sx,sy,&ox,&oy);return rp(r,si,lidx(ox,oy));}
static void train_rblock(const Rot*r,RotBlock*b,int ep){(void)r;RNG q={91};for(int e=0;e<ep;e++)for(int si=0;si<SLOTS;si++){int sx,sy,ox,oy;lunidx(si,&sx,&sy);rr(sx,sy,&ox,&oy);int ti=lidx(ox,oy);for(int k=0;k<40;k++){int wi=ri(&q,SLOTS),blocked=wi==ti;uint32_t *p=blocked?&b->o[si][wi]:&b->z[si][wi];(*p)++;}}}
static float rot_blockp(const RotBlock*b,int si,int wi){uint32_t z=b->z[si][wi],o=b->o[si][wi];return((float)o+.5f)/((float)(z+o)+1.f);}
static float rot_go(const Rot*r,const RotBlock*b,int si,const uint8_t world[SLOTS]){float q=rot_target_base(r,si);for(int wi=0;wi<SLOTS;wi++)if(world[wi])q*=1.f-rot_blockp(b,si,wi);if(q<0)q=0;if(q>1)q=1;return q;}
static void rot_local_base(const Rot*r,const uint8_t in[SLOTS],float out[SLOTS]){for(int oi=0;oi<SLOTS;oi++){double miss=1;int any=0;for(int si=0;si<SLOTS;si++)if(in[si]){any=1;miss*=1.0-rp(r,si,oi);}out[oi]=any?(float)(1.0-miss):0.f;}}
/* ---------- learned lock channel coupling ---------- */
typedef struct{float w[2][2];}Couple;static void train_couple(Couple*c,int ep){float lr=.05f;for(int e=0;e<ep;e++)for(int blocked=0;blocked<2;blocked++){float C=blocked?0.f:1.f,f[2]={C,1.f-C},t[2]={blocked?0.f:1.f,blocked?1.f:0.f};for(int o=0;o<2;o++){float y=c->w[o][0]*f[0]+c->w[o][1]*f[1],er=t[o]-y;for(int k=0;k<2;k++)c->w[o][k]+=lr*er*f[k];}}}static void cg(const Couple*c,float C,float*gm,float*gl){*gm=c->w[0][0]*C+c->w[0][1]*(1-C);*gl=c->w[1][0]*C+c->w[1][1]*(1-C);if(*gm<0)*gm=0;if(*gm>1)*gm=1;if(*gl<0)*gl=0;if(*gl>1)*gl=1;}
/* ---------- learned spawn preview->active patch ---------- */
typedef struct{uint32_t z[PREV][PREV],o[PREV][PREV];}Spawn;static void train_spawn(Spawn*s,int ep){for(int e=0;e<ep;e++)for(int si=0;si<PREV;si++)for(int oi=0;oi<PREV;oi++){uint32_t*p=oi==si?&s->o[si][oi]:&s->z[si][oi];(*p)++;}}static float sp(const Spawn*s,int si,int oi){uint32_t z=s->z[si][oi],o=s->o[si][oi];return((float)o+.5f)/((float)(z+o)+1.f);}static void spawn_patch(const Spawn*s,const uint8_t prev[PREV],float out[PREV]){for(int oi=0;oi<PREV;oi++){double miss=1;int any=0;for(int si=0;si<PREV;si++)if(prev[si]){any=1;miss*=1.0-sp(s,si,oi);}out[oi]=any?(float)(1.0-miss):0.f;}}
typedef struct{uint32_t z[PREV][PREV],o[PREV][PREV];}SpawnBlock;
static void train_spawnblock(SpawnBlock*b,int ep){RNG r={771};for(int e=0;e<ep;e++)for(int si=0;si<PREV;si++)for(int k=0;k<40;k++){int wi=ri(&r,PREV),blocked=wi==si;uint32_t*q=blocked?&b->o[si][wi]:&b->z[si][wi];(*q)++;}}
static float sbp(const SpawnBlock*b,int si,int wi){uint32_t z=b->z[si][wi],o=b->o[si][wi];return((float)o+.5f)/((float)(z+o)+1.f);}
/* ---------- learned line-clear carrier + local propagation ---------- */
typedef struct{uint32_t z[2],o[2];}CellWave;typedef struct{uint32_t zbit[2][2],obit[2][2],zcar[2][2],ocar[2][2];}Prop;static void train_cell(CellWave*m,int ep){for(int e=0;e<ep;e++)for(int x=0;x<2;x++){uint32_t*p=x?&m->o[x]:&m->z[x];(*p)++;}}static float cp(const CellWave*m,int x){uint32_t z=m->z[x],o=m->o[x];return((float)o+.5f)/((float)(z+o)+1.f);}static float rowc(const CellWave*m,const uint8_t*b,int y){float C=1.f;for(int x=0;x<W;x++)C*=cp(m,b[y*W+x]?1:0);return C;}
static void train_prop(Prop*p,int ep){for(int e=0;e<ep;e++)for(int u=0;u<2;u++)for(int c=0;c<2;c++){int bo=c?u:0,co=c?1:0;uint32_t*q=bo?&p->obit[u][c]:&p->zbit[u][c];(*q)++;q=co?&p->ocar[u][c]:&p->zcar[u][c];(*q)++;}}static float pp(uint32_t z,uint32_t o){return((float)o+.5f)/((float)(z+o)+1.f);}
static void prop_step(const Prop*p,uint8_t*b,float*car,int cy){if(cy<=0){car[cy]=0;return;}float C=car[cy];for(int x=0;x<W;x++){int u=b[(cy-1)*W+x];float l=pp(p->zbit[u][1],p->obit[u][1]);b[cy*W+x]=(uint8_t)((C*l+(1-C)*b[cy*W+x])>.5f);b[(cy-1)*W+x]=(uint8_t)(((1-C)*u)>.5f);}car[cy-1]=C*pp(p->zcar[1][1],p->ocar[1][1]);car[cy]=0;}
static int detectrow(const CellWave*c,const uint8_t*b){int best=-1;float bc=.5f;for(int y=0;y<H;y++){float C=rowc(c,b,y);if(C>bc){bc=C;best=y;}}return best;}static void clear_model(const CellWave*c,const Prop*p,uint8_t*b){for(int pass=0;pass<H;pass++){int row=detectrow(c,b);if(row<0)break;float car[H]={0};car[row]=rowc(c,b,row);for(int y=row;y>=0;y--)if(car[y]>.5f)prop_step(p,b,car,y);}}
/* ---------- state + physical reality ---------- */
typedef struct{uint8_t active[N],world[N],pivot[N],preview[PREV],gameover;}State;
static int pivot_xy(const uint8_t*p,int*x,int*y){for(int i=0;i<N;i++)if(p[i]){*x=i%W;*y=i/W;return 1;}return 0;}static void setpivot(uint8_t*p,int x,int y){memset(p,0,N);if(x>=0&&x<W&&y>=0&&y<H)p[y*W+x]=1;}
static void real_clear(uint8_t*b){for(int y=H-1;y>=0;y--){int full=1;for(int x=0;x<W;x++)full&=b[y*W+x];if(full){for(int yy=y;yy>0;yy--)memcpy(b+yy*W,b+(yy-1)*W,W);memset(b,0,W);y++;}}}
static void real_spawn(State*s){uint8_t cand[N]={0};int blocked=0;for(int sy=0;sy<4;sy++)for(int sx=0;sx<4;sx++)if(s->preview[sy*4+sx]){int x=3+sx,y=-1+sy;if(y>=0&&y<H){cand[y*W+x]=1;if(s->world[y*W+x])blocked=1;}}memset(s->active,0,N);memset(s->pivot,0,N);s->gameover=(uint8_t)blocked;if(!blocked){memcpy(s->active,cand,N);setpivot(s->pivot,4,0);}}
static int real_move(State*s,int dir,int lock_on_fail){int blocked=0;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(s->active[y*W+x]){int tx=x+MDX[dir],ty=y+MDY[dir];if(tx<0||tx>=W||ty<0||ty>=H||s->world[ty*W+tx])blocked=1;}if(blocked){if(lock_on_fail){for(int i=0;i<N;i++)if(s->active[i])s->world[i]=1;memset(s->active,0,N);memset(s->pivot,0,N);real_clear(s->world);real_spawn(s);return 1;}return 0;}uint8_t a[N]={0},piv[N]={0};for(int y=0;y<H;y++)for(int x=0;x<W;x++){if(s->active[y*W+x])a[(y+MDY[dir])*W+x+MDX[dir]]=1;if(s->pivot[y*W+x])piv[(y+MDY[dir])*W+x+MDX[dir]]=1;}memcpy(s->active,a,N);memcpy(s->pivot,piv,N);return 0;}
static int real_rot(State*s){int cx,cy;if(!pivot_xy(s->pivot,&cx,&cy))return 0;uint8_t a[N]={0};int blocked=0;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(s->active[y*W+x]){int dx=x-cx,dy=y-cy,tx=cx-dy,ty=cy+dx;if(tx<0||tx>=W||ty<0||ty>=H||s->world[ty*W+tx])blocked=1;else a[ty*W+tx]=1;}if(!blocked)memcpy(s->active,a,N);return 0;}
static int real_step(State*s,int act){if(s->gameover)return 0;if(act==ACT_LEFT)return real_move(s,0,0);if(act==ACT_RIGHT)return real_move(s,1,0);if(act==ACT_DOWN)return real_move(s,2,1);if(act==ACT_ROT)return real_rot(s);if(act==ACT_DROP){for(int k=0;k<64;k++)if(real_move(s,2,1))return 1;}return 0;}
/* ---------- composed learned model tick ---------- */
typedef struct{Move mv;MoveBlock mb;Rot rot;RotBlock rb;Couple cp;Spawn sp;SpawnBlock sb;Couple sc;CellWave cw;Prop prop;}Model;
static void model_init(Model*m){memset(m,0,sizeof(*m));train_move(&m->mv,30);train_mblock(&m->mv,&m->mb,100);train_rot(&m->rot,10);train_rblock(&m->rot,&m->rb,100);train_couple(&m->cp,300);train_spawn(&m->sp,10);train_spawnblock(&m->sb,100);train_couple(&m->sc,300);train_cell(&m->cw,30);train_prop(&m->prop,30);}
static void learned_spawn(const Model*m,const uint8_t prev[PREV],const uint8_t*world,uint8_t*a,uint8_t*piv,float g,uint8_t*gameover){
    float patch[PREV];spawn_patch(&m->sp,prev,patch);uint8_t lw[PREV]={0};for(int sy=0;sy<4;sy++)for(int sx=0;sx<4;sx++){int x=3+sx,y=-1+sy;if(y>=0&&y<H)lw[sy*4+sx]=world[y*W+x];}
    float C=1.f;for(int si=0;si<PREV;si++)if(prev[si]){float q=sp(&m->sp,si,si);for(int wi=0;wi<PREV;wi++)if(lw[wi])q*=1.f-sbp(&m->sb,si,wi);C*=q;}
    float f0=C,f1=1.f-C,gs=m->sc.w[0][0]*f0+m->sc.w[0][1]*f1,gg=m->sc.w[1][0]*f0+m->sc.w[1][1]*f1;float spawn_gain=g*gs;*gameover=(uint8_t)(g*gg>.5f);
    for(int sy=0;sy<4;sy++)for(int sx=0;sx<4;sx++){int x=3+sx,y=-1+sy;if(y>=0&&y<H&&spawn_gain*patch[sy*4+sx]>.5f)a[y*W+x]=1;}
    if(spawn_gain>.5f)setpivot(piv,4,0);
}
static float model_down_once(const Model*m,State*s){if(s->gameover)return 0.f;float C=move_carrier(&m->mv,&m->mb,s->active,s->world,2),gm,gl;cg(&m->cp,C,&gm,&gl);float ma[N],mpiv[N];shifted_probs(&m->mv,s->active,2,ma);shifted_probs(&m->mv,s->pivot,2,mpiv);uint8_t na[N]={0},npiv[N]={0},nw[N];memcpy(nw,s->world,N);for(int i=0;i<N;i++){na[i]=(uint8_t)(gm*ma[i]>.5f);npiv[i]=(uint8_t)(gm*mpiv[i]>.5f);if(gl*(float)s->active[i]>.5f)nw[i]=1;}clear_model(&m->cw,&m->prop,nw);if(gl>.5f){memset(na,0,N);memset(npiv,0,N);learned_spawn(m,s->preview,nw,na,npiv,gl,&s->gameover);}memcpy(s->active,na,N);memcpy(s->world,nw,N);memcpy(s->pivot,npiv,N);return gl;}
static void model_move_lr(const Model*m,State*s,int dir){float C=move_carrier(&m->mv,&m->mb,s->active,s->world,dir);float ma[N],mp[N];shifted_probs(&m->mv,s->active,dir,ma);shifted_probs(&m->mv,s->pivot,dir,mp);for(int i=0;i<N;i++){s->active[i]=(uint8_t)((C*ma[i]+(1-C)*s->active[i])>.5f);s->pivot[i]=(uint8_t)((C*mp[i]+(1-C)*s->pivot[i])>.5f);}}
static void model_rot(const Model*m,State*s){int cx,cy;if(!pivot_xy(s->pivot,&cx,&cy))return;uint8_t in[SLOTS]={0},w[SLOTS]={0};for(int dy=-R;dy<=R;dy++)for(int dx=-R;dx<=R;dx++){int x=cx+dx,y=cy+dy,ii=lidx(dx,dy);if(x<0||x>=W||y<0||y>=H){w[ii]=1;continue;}in[ii]=s->active[y*W+x];w[ii]=s->world[y*W+x];}float C=1.f;for(int si=0;si<SLOTS;si++)if(in[si])C*=rot_go(&m->rot,&m->rb,si,w);float rb[SLOTS];rot_local_base(&m->rot,in,rb);uint8_t old[N];memcpy(old,s->active,N);for(int dy=-R;dy<=R;dy++)for(int dx=-R;dx<=R;dx++){int x=cx+dx,y=cy+dy;if(x<0||x>=W||y<0||y>=H)continue;int ii=lidx(dx,dy);s->active[y*W+x]=(uint8_t)((C*rb[ii]+(1-C)*old[y*W+x])>.5f);}}
static int model_step(const Model*m,State*s,int act){if(s->gameover)return 0;if(act==ACT_LEFT){model_move_lr(m,s,0);return 0;}if(act==ACT_RIGHT){model_move_lr(m,s,1);return 0;}if(act==ACT_DOWN)return model_down_once(m,s)>.5f;if(act==ACT_ROT){model_rot(m,s);return 0;}if(act==ACT_DROP){for(int k=0;k<64;k++)if(model_down_once(m,s)>.5f)return 1;}return 0;}
/* ---------- test generation ---------- */
static const uint16_t BASE[7]={0x00F0,0x0660,0x0270,0x0360,0x0630,0x0710,0x0740};static void preview_shape(int ty,uint8_t p[PREV]){for(int i=0;i<PREV;i++)p[i]=(uint8_t)((BASE[ty]>>i)&1);}
static void local_rotate_bits(uint8_t p[PREV]){uint8_t q[PREV]={0};for(int y=0;y<4;y++)for(int x=0;x<4;x++)if(p[y*4+x]){int dx=x-1,dy=y-1,nx=1-dy,ny=1+dx;if(nx>=0&&nx<4&&ny>=0&&ny<4)q[ny*4+nx]=1;}memcpy(p,q,PREV);}
static int place_piece(RNG*r,State*s,int action,int force_event){memset(s,0,sizeof(*s));preview_shape(ri(r,7),s->preview);uint8_t p[PREV];preview_shape(ri(r,7),p);int rrn=ri(r,4);for(int k=0;k<rrn;k++)local_rotate_bits(p);for(int tries=0;tries<200;tries++){int cx=2+ri(r,W-4),cy=3+ri(r,H-8);memset(s->active,0,N);setpivot(s->pivot,cx,cy);int ok=1,cells=0;for(int sy=0;sy<4;sy++)for(int sx=0;sx<4;sx++)if(p[sy*4+sx]){int x=cx+sx-1,y=cy+sy-1;if(x<0||x>=W||y<0||y>=H){ok=0;continue;}s->active[y*W+x]=1;cells++;}if(!ok||cells!=4)continue;for(int k=0;k<15;k++){int x=ri(r,W),y=6+ri(r,H-6);if(!s->active[y*W+x])s->world[y*W+x]=1;}if(force_event){if(action==ACT_DOWN||action==ACT_DROP){int cand[N],n=0;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(s->active[y*W+x]&&y+1<H)cand[n++]=y*W+x;if(!n)continue;int ci=cand[ri(r,n)],x=ci%W,y=ci/W;s->world[(y+1)*W+x]=1;if(ri(r,2)){for(int xx=0;xx<W;xx++)if(!s->active[y*W+xx])s->world[y*W+xx]=1;}}else if(action==ACT_LEFT||action==ACT_RIGHT){int dir=action==ACT_LEFT?0:1,cand[N],n=0;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(s->active[y*W+x]){int tx=x+MDX[dir];if(tx>=0&&tx<W)cand[n++]=y*W+x;}if(n){int ci=cand[ri(r,n)],x=ci%W,y=ci/W;s->world[y*W+x+MDX[dir]]=1;}}else if(action==ACT_ROT){int px=0,py=0;(void)pivot_xy(s->pivot,&px,&py);int cand[N],n=0;for(int y=0;y<H;y++)for(int x=0;x<W;x++)if(s->active[y*W+x]){int dx=x-px,dy=y-py,tx=px-dy,ty=py+dx;if(tx>=0&&tx<W&&ty>=0&&ty<H)cand[n++]=ty*W+tx;}if(n)s->world[cand[ri(r,n)]]=1;}}for(int i=0;i<N;i++)if(s->active[i]&&s->world[i])s->world[i]=0;for(int y=0;y<4;y++)for(int x=2;x<8;x++)if(!s->active[y*W+x])s->world[y*W+x]=0;return 1;}return 0;}
typedef struct{unsigned long long n,full,byact[ACTS],okact[ACTS],lockn,lockok;}Stat;
static void audit(const Model*m,int samples,uint64_t seed){RNG r={seed};Stat st={0};for(int i=0;i<samples;i++){int act=ri(&r,ACTS),force=ri(&r,2);State a,b;if(!place_piece(&r,&a,act,force)){i--;continue;}b=a;int lr=real_step(&a,act),lm=model_step(m,&b,act);(void)lm;int ok=eq(a.active,b.active,N)&&eq(a.world,b.world,N)&&eq(a.pivot,b.pivot,N)&&a.gameover==b.gameover;st.n++;st.full+=ok;st.byact[act]++;st.okact[act]+=ok;if(lr){st.lockn++;st.lockok+=ok;}}
const char*nm[ACTS]={"left","right","down","rot","drop"};printf("integrated n=%llu exact=%7.3f%% lock_events=%llu lock_exact=%7.3f%%\n",st.n,100.0*st.full/st.n,st.lockn,st.lockn?100.0*st.lockok/st.lockn:0);for(int a=0;a<ACTS;a++)printf("  %-5s %llu/%llu = %7.3f%%\n",nm[a],st.okact[a],st.byact[a],100.0*st.okact[a]/st.byact[a]);}
static void init_episode(RNG*r,State*s){memset(s,0,sizeof(*s));uint8_t cur[PREV];preview_shape(ri(r,7),cur);for(int sy=0;sy<4;sy++)for(int sx=0;sx<4;sx++)if(cur[sy*4+sx]){int x=3+sx,y=-1+sy;if(y>=0&&y<H)s->active[y*W+x]=1;}setpivot(s->pivot,4,0);preview_shape(ri(r,7),s->preview);}
static void audit_rollout(const Model*m,int episodes,int maxsteps,uint64_t seed){
    RNG r={seed};unsigned long long steps=0,exact=0,locks=0,gameovers=0,failact[ACTS]={0};int completed=0;int first_fail_ep=-1,first_fail_t=-1,first_fail_act=-1,first_lr=0,first_lm=0,first_da=0,first_dw=0,first_dp=0;float first_rotC=-1.f;int first_localW=0,first_rotBlocked=-1;
    for(int ep=0;ep<episodes;ep++){
        State real,mod;init_episode(&r,&real);mod=real;
        for(int t=0;t<maxsteps;t++){
            int act;int u=ri(&r,100);if(u<18)act=ACT_LEFT;else if(u<36)act=ACT_RIGHT;else if(u<50)act=ACT_ROT;else if(u<70)act=ACT_DOWN;else act=ACT_DROP;
            float preC=-1.f;int preW=0,preBlocked=-1;if(act==ACT_ROT){int cx=0,cy=0;if(pivot_xy(mod.pivot,&cx,&cy)){uint8_t lin[SLOTS]={0},lw[SLOTS]={0};for(int dy=-R;dy<=R;dy++)for(int dx=-R;dx<=R;dx++){int xx=cx+dx,yy=cy+dy,ii=lidx(dx,dy);if(xx<0||xx>=W||yy<0||yy>=H){lw[ii]=1;preW++;}else{lin[ii]=mod.active[yy*W+xx];lw[ii]=mod.world[yy*W+xx];preW+=lw[ii];}}preC=1.f;preBlocked=0;for(int si=0;si<SLOTS;si++)if(lin[si]){preC*=rot_go(&m->rot,&m->rb,si,lw);int sx,sy,ox,oy;lunidx(si,&sx,&sy);rr(sx,sy,&ox,&oy);if(lw[lidx(ox,oy)])preBlocked=1;}}}
            int lr=real_step(&real,act),lm=model_step(m,&mod,act);
            int ok=(lr==lm)&&eq(real.active,mod.active,N)&&eq(real.world,mod.world,N)&&eq(real.pivot,mod.pivot,N)&&real.gameover==mod.gameover;
            steps++;exact+=ok;if(lr)locks++;if(real.gameover)gameovers++;
            if(!ok){failact[act]++;if(first_fail_ep<0){first_fail_ep=ep;first_fail_t=t;first_fail_act=act;first_lr=lr;first_lm=lm;for(int q=0;q<N;q++){first_da+=(real.active[q]!=mod.active[q]);first_dw+=(real.world[q]!=mod.world[q]);first_dp+=(real.pivot[q]!=mod.pivot[q]);}first_rotC=preC;first_localW=preW;first_rotBlocked=preBlocked;}break;}
            if(lr){if(real.gameover||mod.gameover)break;uint8_t np[PREV];preview_shape(ri(&r,7),np);memcpy(real.preview,np,PREV);memcpy(mod.preview,np,PREV);}
            if(t==maxsteps-1)completed++;
        }
    }
    printf("rollout episodes=%d maxsteps=%d compared_steps=%llu exact=%llu/%llu=%7.3f%% locks=%llu gameovers=%llu full_horizon=%d first_fail=%d:%d act=%d lr/lm=%d/%d diffA/W/P=%d/%d/%d rotC=%.4f localW=%d actualBlocked=%d\n",episodes,maxsteps,steps,exact,steps,100.0*exact/steps,locks,gameovers,completed,first_fail_ep,first_fail_t,first_fail_act,first_lr,first_lm,first_da,first_dw,first_dp,first_rotC,first_localW,first_rotBlocked);
    printf("rollout failures by action: L=%llu R=%llu D=%llu Rot=%llu Drop=%llu\n",failact[0],failact[1],failact[2],failact[3],failact[4]);
}
int main(){Model m;model_init(&m);puts("BPC Tetris Minimal Integrated v1.4 | no tetromino-rule training in model primitives");audit(&m,20000,12345);audit_rollout(&m,2000,100,98765);return 0;}
